### ISSUE TITLE
I can't run it

### ISSUE THREAD

**Issue by irabbit666666** [frankli0324/chaos_vm_disasm#1]
When I try to run it,
:
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from parser import parse
  File "/home/iubuntu/Desktop/chaos_vm_disasm/parser/__init__.py", line 1, in <module>
    from .parser import parse
  File "/home/iubuntu/Desktop/chaos_vm_disasm/parser/parser.py", line 36, in <module>
    def match(pattern, ops) -> tuple[int, list]:
TypeError: 'type' object is not subscriptable

**Comment by frankli0324** [comment]
please use python >= 3.9, or prepend `from __future__ import annotations` to `parser.py` in python >= 3.7, or replace `tuple[int, list]` with `typing.Tuple[int, list]` (after importing `typing`, of course)
